### ISSUE TITLE
adapter.js issue

### ISSUE THREAD

**Issue by ayanb1991** [baitic/sails-oradb#4]
I have found that at line 1059 in adapter.js file there is a line as below.
var selectQuery = 'select \* from "'+table+'" order by "id" desc'
here the **"id"** is creating problem for the oracle table which do not use keyword **'id'** as there primary key columnName.

same on line 1336

**Comment by segarcialo** [comment]
Resolved. https://github.com/baitic/sails-oradb/issues/7
